version: "1.0"
info:
  model: int-scaffold
packages:
- name: IT_AC_Demo_IWHIProject
  gitServerName: AC_IWHI
  gitUrl: https://github.com/AlessandroChinnici
  gitUsername: AlessandroChinnici
  gitBranch: main
